# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "6.0.0"
    }
  }
}

provider "aws" {
  region = "eu-north-1"
  assume_role {
    role_arn     = "arn:aws:iam::155023195342:role/InfraAsCode"
    session_name = "InfraAsCode"
  }
}
