## Generated by gomplate at 2025-06-27 23:12:30.365141772 +0200 CEST m=+0.019575545


module "vpc" {
  source = "github.com/terraform-aws-modules/terraform-aws-vpc?ref=v5.17.0"

  azs  = local.azs
  cidr = "10.80.0.0/16"

  enable_nat_gateway = true
  single_nat_gateway = true

  private_subnets = [for k in range(0, length(local.azs)) : cidrsubnet("10.80.0.0/16", 8, k + 8)]
  public_subnets  = [for k in range(0, length(local.azs)) : cidrsubnet("10.80.0.0/16", 12, k + 8)]
  intra_subnets   = [for k in range(0, length(local.azs)) : cidrsubnet("10.80.0.0/16", 8, k + 12)]

  enable_ipv6                                   = false
  public_subnet_assign_ipv6_address_on_creation = false

  public_subnet_ipv6_prefixes  = [0, 1, 2]
  private_subnet_ipv6_prefixes = [3, 4, 5]
  intra_subnet_ipv6_prefixes   = [6, 7, 8]
}
